= Monster Hunter scripts

This repository contains the source code for http://mhapi.info, a site for
monster hunter related calculators and tools. It also contains scripts that
can be used directly from the command line, and python modules that can be used
to build other monster hunter related tools.

== Dependencies

Tested using Python 2.7, might work with 2.6. Uses sqlite3, which is part of
the standard library now but I'm not sure it's always compiled in by default
in all Python distributions (e.g. for Windows or Mac OS X).

== Acknowledgements

The bundled monster hunter db is from the excellent
link:https://github.com/kamegami13/MonsterHunter4UDatabase[MonsterHunter4UDatabase]
Android app by DavianCorp, which is also MIT licensed. See
link:db/COPYING.mh4udb[] for license details.

== Example usage

For a list of quests and hunts providing the specified monster part:

 bin/mhrewards.py "Zinogre Jasper"

This gives detailed expected values for the item from different sources,
including quest rewards, carves, capture, and shiny drops. It also gives
recommendations for which quests and strategy (capture or kill) will give the
best results. See link:RECOMMENDATIONS.adoc[] for a more detailed explanation of
the output.

For more manual calculations, mhprob.py can be used directly. The quest
"Plain Dangerous" in 3U has 2 fixed rewards in A, one in B. Diablos hardhorns
have a 5% chance:

 bin/mhprop.py 5 2 3 69
 bin/mhprop.py 5 1 1 69

For great luck, you would replace 69 with 90. The output includes both expected
value and probability of getting at least one.

== Math

Monster hunter rewards can be modeled using the Binomial distribution. The most
popular method I've seen online is to calculate the probability of getting at
least one. I prefer to use expected (mean) value, which is easier to calculate
and provides a more intuitive quantity. For
more information see the
link:http://en.wikipedia.org/wiki/Expected_value[Wikipedia article] on expected
value, and the description of how to calculate expected value on the
link:http://en.wikipedia.org/wiki/Binomial_distribution#Mean_and_variance[Binomial distribution].
